#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory

case "$1" in
  start)
 	echo "Starting lighttpd..."
	mkdir -p /var/log/lighttpd
	mkdir -p /var/run/lighttpd
	/usr/sbin/lighttpd -f /usr/etc/lighttpd/lighttpd.conf
	;;
  stop)
	echo -n "Stopping lighttpd..."

	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

